name=OmniLiteFuzzy
version=1.0.0
author=Zadid Taqwa
maintainer=Zadid Taqwa
sentence=A lightweight, OOP-based Fuzzy Logic library supporting Mamdani, Sugeno, and Tsukamoto.
paragraph=OmniLiteFuzzy is designed for IoT and microcontrollers with strict memory constraints. It avoids dynamic memory allocation to prevent heap fragmentation while supporting multiple fuzzy inference methods.
category=Data Processing
url=https://github.com/Akiyaaaaaa/omni-lite-fuzzy
architectures=*